#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC = clang++
OPTIMIZE = false
DEBUG     = no
ARCH = sm_70
LAUNCHER  =

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = main.cu

obj = $(source:.cu=.o)

headers =   src/bb_bin.cuh  src/bb_comput_common.cuh  src/bb_comput_l_keys.cuh  src/bb_comput_l.cuh  src/bb_comput_s_keys.cuh  src/bb_comput_s.cuh  src/bb_exch_keys.cuh  src/bb_exch.cuh  src/bb_segsort_common.cuh  src/bb_segsort_keys.cuh  src/bb_segsort.cuh

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS = $(EXTRA_CFLAGS) -std=c++14 -Wall --offload-arch=$(ARCH) --cuda-path=$(CUDA_HOME) --save-temps -I$(CUDA_HOME)/nvidia/targets/ppc64le-linux/include

# Linker Flags
LDFLAGS = -Wl,-rpath,${CUDA_HOME}/nvidia/lib64 -L${CUDA_HOME}/nvidia/lib64 -lcuda -lcudadevrt -lcudart_static -lrt -lpthread -ldl

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif
#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj) Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cu $(headers) Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -rf $(program) $(obj)

run: $(program)
	$(LAUNCHER) ./$(program)

