site_name: Mneme
repo_url: https://github.com/Olympus-HPC/Mneme
repo_name: Olympus-HPC/Mneme 
theme:
  name: material
  logo: assets/images/MnemeLogoNotext.svg
  favicon: assets/images/MnemeLogoNotext.svg

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight


nav:
  - Home: index.md
  - Getting Started: usage/getting-started.md
  - Usage:
      - Getting Started: usage/getting-started.md
      - CLI: usage/cli.md
      - Artifacts: usage/artifacts.md
      - Tune: usage/tune.md
      - Install: usage/install.md
      - Verification: usage/verification.md
  - Concepts:
    - Overview: concepts/overview.md
    - Execution Phases: concepts/mneme-phases.md
    - Static & Dynamic Hashes: concepts/static-dynamic.md
    - Artifacts: concepts/artifacts.md
    - Why LLVM IR as a boundary : concepts/llvm-boundary.md
    - Replay Configuration: concepts/replay-configuration.md 
    - Tune: concepts/tune.md
  - Develop:
      - Python: dev/python.md
      - C++: dev/cpp.md
  - Examples: examples.md
  - Limitations: limitations.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy"
            show_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight


copyright: Copyright &copy; 2024 - 2025 Lawrence Livermore National Security, LLC and mneme project contributors.
