site_name: Mneme
repo_url: https://github.com/Olympus-HPC/Mneme
repo_name: Olympus-HPC/Mneme 
theme:
  name: material
  logo: assets/images/MnemeLogoNotext.svg
  favicon: assets/images/MnemeLogoNotext.svg

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight


nav:
  - Home: index.md

  - Usage:
      - Install: usage/install.md
      - Record: usage/record.md
      - Replay: usage/replay.md

  - Develop:
      - Python: dev/python.md
      - C++: dev/cpp.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy"
            show_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight


copyright: Copyright &copy; 2024 - 2025 Lawrence Livermore National Security, LLC and mneme project contributors.
