site_name: Mneme
repo_url: https://github.com/Olympus-HPC/Mneme
repo_name: Olympus-HPC/Mneme 
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

nav:
  - Home: index.md
  - Install: install.md
  - Usage:
      - Python: usage/python.md
      - C++: usage/cpp.md
  - API:
      - Python API: api/python.md
      - C++ API (Doxygen): cpp-api/index.html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google  # or "numpy"
            show_source: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight


copyright: Copyright &copy; 2024 - 2025 Lawrence Livermore National Security, LLC and mneme project contributors.
