# pytest.ini (in root/)
[pytest]
testpaths =
    python/tests

addopts =
    --cov=mneme
    --cov-report=term-missing
    --cov-report=xml
    --cov-config=pytest.ini

[coverage:run]
omit =
    mneme/llvm/*
