from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Iterator, Any

from mneme.logging import logger
from mneme.mneme_types import ExperimentConfiguration


class SamplingStrategy(ABC):
    """
    Abstract base class for parameter sampling strategies.

    A ``SamplingStrategy`` defines how candidate parameter dictionaries are
    generated from a :class:`SearchSpace`. Concrete implementations determine
    whether sampling is exhaustive, random, adaptive, or driven by an external
    optimization framework (e.g., Optuna).

    Implementations must provide an iterator interface that yields parameter
    dictionaries compatible with the associated :class:`SearchSpace`.
    """

    @abstractmethod
    def __iter__(self) -> Iterator[Tuple[ExperimentConfiguration, Any]]:
        """Return an iterator that yields configs."""
        pass


class ExhaustiveSamplingStrategy(SamplingStrategy):
    """
    Exhaustive sampling strategy over the entire search space.

    This strategy enumerates **all** valid combinations of parameters as defined
    by the associated :class:`SearchSpace`. It is intended primarily for small
    search spaces where full enumeration is feasible.

    Notes
    -----
    * This strategy has **not been tested at all** and should be considered
      as proof of concept.
    * Exhaustive enumeration may become prohibitively expensive for large or
      high-dimensional search spaces.
    """

    def __init__(self, search_space):
        """
        Construct an exhaustive sampler.

        Parameters
        ----------
        search_space : SearchSpace
            Search space providing the parameter definitions and exhaustive
            enumeration logic.
        """
        self.space = search_space

    def __iter__(self) -> Iterator[Tuple[ExperimentConfiguration, Any]]:
        """
        Yield all parameter combinations from the search space.

        Returns
        -------
        Iterator[dict]
            Iterator over parameter dictionaries produced by
            :meth:`SearchSpace.sample_exhaustive`.
        """
        for params in self.space.sample_exhaustive():
            yield params


class RandomSamplingStrategy(SamplingStrategy):
    """
    Random sampling strategy over the search space.

    This strategy draws a fixed number of independent samples from the search
    space using the search space’s random sampling logic.

    Notes
    -----
    * This strategy has **not been tested at all** and should be considered
      as proof of concept.
    * Sampling does not guarantee coverage or uniqueness of configurations.
    """

    def __init__(self, search_space, num_samples: int):
        """
        Construct a random sampler.

        Parameters
        ----------
        search_space : SearchSpace
            Search space providing the parameter definitions and random sampling
            logic.
        num_samples : int
            Number of random samples to generate.
        """
        self.space = search_space
        self.num_samples = num_samples

    def __iter__(self) -> Iterator[Tuple[ExperimentConfiguration, Any]]:
        """
        Yield randomly sampled parameter dictionaries.

        Returns
        -------
        Iterator[dict]
            Iterator yielding ``num_samples`` independently sampled parameter
            dictionaries.
        """
        for _ in range(self.num_samples):
            yield self.space.sample_random()


class OptunaSamplingStrategy(SamplingStrategy):
    """
    Optuna-driven adaptive sampling strategy.

    This strategy delegates sampling decisions to an Optuna ``Study`` object.
    Parameter suggestions are generated by invoking the search space’s Optuna
    sampling logic, which typically binds Optuna ``Trial`` objects to parameter
    definitions.

    The iterator yields samples until the requested number of trials has been
    reached, accounting for trials that may already exist in the study (e.g.,
    when resuming from a persistent Optuna backend).
    """

    def __init__(self, search_space, study, n_trials):
        """
        Construct an Optuna-based sampling strategy.

        Parameters
        ----------
        search_space : SearchSpace
            Search space providing Optuna-aware sampling logic.
        study : optuna.Study
            Optuna study object managing trials and optimization state.
        n_trials : int
            Total number of trials to execute (including any existing trials
            already present in the study).
        """
        self.space = search_space
        self.study = study
        self.n_trials = n_trials
        logger.debug(
            f"{self.__class__.__name__} Total number of previously executed trials are {len(self.study.trials)} and total requested trials are {self.n_trials}"
        )

    def __iter__(self) -> Iterator[Tuple[ExperimentConfiguration, Any]]:
        """
        Yield Optuna-suggested parameter dictionaries.

        Iteration continues until the number of trials in the associated study
        reaches ``n_trials``.

        Returns
        -------
        Iterator[dict]
            Iterator yielding parameter dictionaries produced via Optuna.
        """
        while len(self.study.trials) < self.n_trials:
            params = self.space.sample_optuna(self.study)
            yield params
