#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC = clang++
OPTIMIZE = false
DEBUG     = no
ARCH = sm_70
LAUNCHER  =

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = hotspot.cu

obj = $(source:.cu=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS = $(EXTRA_CFLAGS) -std=c++14 -Wall --offload-arch=$(ARCH) --cuda-path=$(CUDA_HOME) --save-temps -I$(CUDA_HOME)/nvidia/targets/ppc64le-linux/include

# Linker Flags
LDFLAGS = -Wl,-rpath,${CUDA_HOME}/nvidia/lib64 -L${CUDA_HOME}/nvidia/lib64 -lcuda -lcudadevrt -lcudart_static -lrt -lpthread -ldl

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif
#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj) Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

$(obj): hotspot.cu hotspot.h kernel.h
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -rf $(program) $(obj) *.out

run: $(program)
	$(LAUNCHER) ./$(program) 512 2 200 ../data/hotspot/temp_512 ../data/hotspot/power_512 output_512.out
