#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC = clang++
OPTIMIZE = false
DEBUG     = no
ARCH = sm_70
LAUNCHER  =

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = main.cu dslash.cu kernels.cu

obj = $(source:.cu=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
# Double precision the grid size is 32^4 
CFLAGS = $(EXTRA_CFLAGS) -std=c++14 -DMILC_COMPLEX -DLDIM=32 -DPRECISION=1 -Wall --offload-arch=$(ARCH) -fopenmp -I../include --cuda-path=$(CUDA_HOME) --save-temps -I$(CUDA_HOME)/nvidia/targets/ppc64le-linux/include -ffast-math

# Linker Flags
LDFLAGS = -Wl,-rpath,${CUDA_HOME}/nvidia/lib64 -L${CUDA_HOME}/nvidia/lib64 -lcuda -lcudadevrt -lcudart_static -lrt -lpthread -ldl

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g -DDEBUG
  LDFLAGS  += -g
endif


# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3 -use_fast_math
endif

#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj)
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cu dslash.h
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -rf $(program) $(obj)

run: $(program)
	$(LAUNCHER) ./$(program) 256

