# Auto-generated by setup.py
from __future__ import annotations
from pathlib import Path
import sys

_PKG_DIR = Path(__file__).resolve().parents[1]
_NATIVE = _PKG_DIR / "native"
_LIB64 = _NATIVE / "lib64"

def _lib(name_linux: str, name_darwin: str) -> str:
    return str(_LIB64 / (name_darwin if sys.platform == "darwin" else name_linux))

MNEME_CORE_LIB    = _lib("libmneme.so",         "libmneme.dylib")
MNEME_PROFILE_LIB = _lib("libmneme_profile.so", "libmneme_profile.dylib")
MNEME_RECORD_LIB  = _lib("librecord.so",        "librecord.dylib")
MNEME_CONFIG_FILE = str(_NATIVE / "config.json")
