#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC = clang++
OPTIMIZE = false
DEBUG     = no
ARCH = sm_70
VERIFY    = no
LAUNCHER  =

#===============================================================================
# Program name & source code list
#===============================================================================

program = main

source = init.cu  io.cu  main.cu

obj = $(source:.cu=.o)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS = $(EXTRA_CFLAGS) -std=c++14 -Wall --offload-arch=$(ARCH) --cuda-path=$(CUDA_HOME) --save-temps -I$(CUDA_HOME)/nvidia/targets/ppc64le-linux/include

# Linker Flags
LDFLAGS = -Wl,-rpath,${CUDA_HOME}/nvidia/lib64 -L${CUDA_HOME}/nvidia/lib64 -lcuda -lcudadevrt -lcudart_static -lrt -lpthread -ldl

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS +=-O3
endif

ifeq ($(VERIFY),yes)
  CFLAGS +=-DVERIFY
endif

#===============================================================================
# Targets to Build
#===============================================================================

$(program): $(obj) Makefile
	$(CC) $(CFLAGS) $(obj) -o $@ $(LDFLAGS)

%.o: %.cu SimpleMOC-kernel_header.h Makefile
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -rf $(program) $(obj)

run: $(program)
	$(LAUNCHER) ./$(program) -s 5000000 -e 128 -n 10
