#===============================================================================
# User Options
#===============================================================================

# Compiler can be set below, or via environment variable
CC = clang++
OPTIMIZE = false
DEBUG     = no
ARCH = sm_70
LAUNCHER  =

#===============================================================================
# Program name & source code list
#===============================================================================

program = sph

build: $(program)

#===============================================================================
# Sets Flags
#===============================================================================

# Standard Flags
CFLAGS = $(EXTRA_CFLAGS) -std=c++14 -Wall --offload-arch=$(ARCH) --cuda-path=$(CUDA_HOME) --save-temps -I$(CUDA_HOME)/nvidia/targets/ppc64le-linux/include

# Linker Flags
LDFLAGS = -Wl,-rpath,${CUDA_HOME}/nvidia/lib64 -L${CUDA_HOME}/nvidia/lib64 -lcuda -lcudadevrt -lcudart_static -lrt -lpthread -ldl

# Debug Flags
ifeq ($(DEBUG),yes)
  CFLAGS += -g
  LDFLAGS  += -g
endif

# Optimization Flags
ifeq ($(OPTIMIZE),yes)
  CFLAGS += -O3
endif

#===============================================================================
# Targets to Build
#===============================================================================

$(program): fileio.o fluid.o geometry.o
	$(CC) $(CFLAGS) $+ -o $@ $(LDFLAGS)

fileio.o: fileio.cu
	$(CC) $(CFLAGS) -c $< -o $@

fluid.o: fluid.cu
	$(CC) $(CFLAGS) -c $< -o $@

geometry.o: geometry.cu
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -rf $(program) fileio.o fluid.o geometry.o *.csv

run: $(program)
	$(LAUNCHER) ./$(program)
