function(add_mneme target)
get_target_property(_proteus_type proteus TYPE)
	add_proteus(${target} ENABLE_AGGRESSIVE)
	if(_proteus_type STREQUAL "STATIC_LIBRARY")
	    message(STATUS "Proteus is a static library")
    	    target_link_options(${target} PRIVATE -Wl,--wrap=__jit_launch_kernel)
    	    target_link_libraries(${target} PRIVATE mneme_wrapper)
	endif()
endfunction()
