if(MNEME_ENABLE_HIP)
    SET(lang HIP)
else()
    SET(lang CUDA)
endif()

function(BUILD_UNIT_TEST exe)
  message(STATUS "Building test ${exe} ${ARGN}")
  add_executable(${exe} ${ARGN})
  target_include_directories(${exe} PRIVATE ${CMAKE_SOURCE_DIR}/include/)
  if (MNEME_ENABLE_HIP)
    message(STATUS "Building test ${exe}")
    target_link_libraries(${exe} PRIVATE hip::host)
  endif()
  target_link_libraries(${exe} PRIVATE ${LLVM_AVAILABLE_LIBS})
endfunction()

BUILD_UNIT_TEST(random_alloc_dealloc random_alloc_dealloc.cpp)
#add_test(NAME Mem::Reserve::Addr COMMAND reserve_addr)
